// <auto-generated />
namespace WebAppMysql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class hamza : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hamza));
        
        string IMigrationMetadata.Id
        {
            get { return "202212210149340_hamza"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
